In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("/content/student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [ ]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

<ipython-input-8-f2945ec72437>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In [ ]:
print(data.head())


  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  internet romantic  famrel  freetime  goout Dalc Walc health absences passed  
0       no       no       4         3      4    1    1      3        6     no  
1      yes       no       5         3      3    1    1      3        4     no  
2      yes       no       4         3      2    2    3      3       10    yes  
3      yes      yes       3         2      2    1    1      5        2    yes  
4       no       no       4         3      2    1    2      5        4    yes  

[5 rows x 31 columns]


In [ ]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)


0.7859065601066979


In [ ]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])


[[15.12896572 10.24410393 -0.90163263  6.1518365  10.24410393]
 [15.12896572 15.12896572 -0.90163263  6.1518365  10.49716289]
 [11.93945794  9.45249754 -0.90163263 10.04155226  7.97630066]
 ...
 [ 7.97630066  9.45249754 15.3468132  10.04155226 10.04155226]
 [13.80301713  5.32464582 15.3468132   6.1518365   6.1518365 ]
 [ 9.45249754 12.09813779 15.3468132   6.1518365  15.12896572]] [[[15 15  2  0  0]
  [ 9 11  3  0  2]
  [ 6  0  2  0  0]
  [ 8  7  2  3  0]
  [ 9 11  3  0  2]]

 [[15 15  2  0  0]
  [15 15  2  0  0]
  [ 6  0  2  0  0]
  [ 8  7  2  3  0]
  [11 11  4  0  8]]

 [[13 11  3  1 40]
  [ 8 10  2  0  6]
  [ 6  0  2  0  0]
  [12 10  2  0  8]
  [ 5  9  2  2  6]]

 ...

 [[ 5  9  2  2  6]
  [ 8 10  2  0  6]
  [16 15  3  0  9]
  [12 10  2  0  8]
  [12 10  2  0  8]]

 [[13 14  3  0  4]
  [ 7  6  1  1  0]
  [16 15  3  0  9]
  [ 8  7  2  3  0]
  [ 8  7  2  3  0]]

 [[ 8 10  2  0  6]
  [13 12  1  0  0]
  [16 15  3  0  9]
  [ 8  7  2  3  0]
  [15 15  2  0  0]]] [array([[15, 11,  0,  0, 11]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle
import pickle

data=pd.read_csv('student-mat.csv')
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)


linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)


0.8655207614086378


<ipython-input-11-a0b7005493de>:10: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))
